FROM chuanwen/cowsay:latest
ENTRYPOINT [ "/usr/games/cowsay" ]
CMD [ "#VQV Trybe" ]

# COMMANDS
# docker container run cowsay
# docker container run cowsay Go Trybe!
# docker container run cowsay -f dragon-and-cow "VQM TRYBE"
# docker container run cowsay -l (para verificar quais animais podem ser printados)